export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const INSTRUCTOR_LOADING = "USER_LOADING";
export const INSTRUCTOR_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const GET_ACTIVE_LABS = "GET_ACTIVE_LABS";
export const CLEAR_ACTIVE_LABS = "CLEAR_ACTIVE_LABS";

export const GET_COMPLETED_LABS = "GET_COMPLETED_LABS";
export const CLEAR_COMPLETED_LABS = "CLEAR_COMPLETED_LABS";

export const GET_LABS = "GET_LABS";
export const CLEAR_LABS = "CLEAR_LABS";
export const CREATE_LAB = "CREATE_LAB";
export const ADD_LABCYCLE = "ADD_LABCYCLE";
export const ADD_ACTIVE_LAB = "ADD_ACTIVE_LAB";

export const MARK_COMPLETED = "MARK_COMPLETED";
export const ADD_COMPLETED_LAB = "ADD_COMPLETED_LAB";
